services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - sim

  sim:
    image: nodered/node-red:latest
    volumes:
      - ./sim:/data
